name: Test

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Install sops
      run: |
        echo "$PATH"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        curl -L "https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64" -o "${GITHUB_WORKSPACE}/bin/sops"
        chmod +x "${GITHUB_WORKSPACE}/bin/sops"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
